import type { Metadata } from "next";
import { Geist, Geist_Mono, Michroma } from "next/font/google";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pl">

          {children}

    </html>
  );
}
